services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: [
        "uvicorn", 
        "app:app", 
        "--host", "0.0.0.0", 
        "--port", "8080", 
        "--reload"
      ]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthcheck || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge